import type { Preset } from '../types';

export const PRESETS: Preset[] = [
  {
    id: 'greenhouse-v2',
    name: 'Greenhouse 4m V2',
    description: '4m V2 dome · 3/4" PVC · smooth organic hubs',
    settings: {
      freq: 2,
      diam: 4.0,
      trunc: 0.625,
      matType: 'round',
      materialStockId: 'pvc-0.75',
      tol: 0.3,
      wall: 4,
      hubStyle: 'organic',
      bodyScale: 1.6,
      junctionMeet: 1.0,
      chamfer: 2.0,
      surfaceSmooth: 0.65,
      socketDepth: 0.9,
      meshSubdivide: true,
      screwHoles: true,
      screwDia: 4.2,
      baseThickness: 4,
      baseScale: 1.35,
    },
  },
  {
    id: 'event-emt',
    name: 'Event 6m EMT',
    description: 'Large V3 event dome · 1" EMT · chunky blended nodes',
    settings: {
      freq: 3,
      diam: 6.0,
      trunc: 0.625,
      matType: 'round',
      materialStockId: 'emt-1',
      tol: 0.2,
      wall: 5,
      hubStyle: 'organic',
      bodyScale: 1.75,
      junctionMeet: 1.15,
      chamfer: 2.5,
      surfaceSmooth: 0.7,
      socketDepth: 0.95,
      meshSubdivide: true,
      screwHoles: true,
      screwDia: 3.3,
      baseThickness: 5,
      baseScale: 1.4,
    },
  },
  {
    id: 'playground-v1',
    name: 'Playground V1',
    description: 'Small V1 climber · 1/2" PVC · soft pebble hubs',
    settings: {
      freq: 1,
      diam: 2.5,
      trunc: 0.75,
      matType: 'round',
      materialStockId: 'pvc-0.5',
      tol: 0.35,
      wall: 4,
      hubStyle: 'organic',
      bodyScale: 1.85,
      junctionMeet: 1.2,
      chamfer: 1.5,
      surfaceSmooth: 0.85,
      socketDepth: 0.85,
      meshSubdivide: true,
      screwHoles: false,
      baseThickness: 4,
      baseScale: 1.4,
    },
  },
  {
    id: 'shed-timber-organic',
    name: 'Shed 3m Timber (Organic)',
    description: '3m dome · 1×2 lumber · blended organic sockets',
    settings: {
      freq: 2,
      diam: 3.0,
      trunc: 0.5,
      matType: 'rect',
      materialStockId: 'lumber-1x2',
      tol: 0.35,
      wall: 3.5,
      hubStyle: 'organic',
      bodyScale: 1.5,
      junctionMeet: 1.05,
      chamfer: 2.0,
      surfaceSmooth: 0.6,
      socketDepth: 0.9,
      meshSubdivide: true,
      screwHoles: true,
      screwDia: 3.3,
      baseThickness: 4,
      baseScale: 1.3,
    },
  },
  {
    id: 'shed-timber-sharp',
    name: 'Shed 3m Timber (Sharp)',
    description: '3m dome · 1×2 lumber · crisp prismatic sockets',
    settings: {
      freq: 2,
      diam: 3.0,
      trunc: 0.5,
      matType: 'rect',
      materialStockId: 'lumber-1x2',
      tol: 0.35,
      wall: 3.5,
      hubStyle: 'sharp',
      bodyScale: 1.25,
      junctionMeet: 1.1,
      chamfer: 1.5,
      surfaceSmooth: 0.3,
      socketDepth: 0.95,
      screwHoles: true,
      screwDia: 3.3,
      baseThickness: 4,
      baseScale: 1.3,
    },
  },
  {
    id: 'pavilion-2x6',
    name: 'Pavilion 5m 2×6',
    description: 'Heavy V2 timber pavilion · 2×6 rafters · stout cores',
    settings: {
      freq: 2,
      diam: 5.0,
      trunc: 0.625,
      matType: 'rect',
      materialStockId: 'lumber-2x6',
      tol: 0.4,
      wall: 6,
      hubStyle: 'organic',
      bodyScale: 1.35,
      junctionMeet: 1.2,
      chamfer: 2.5,
      surfaceSmooth: 0.5,
      socketDepth: 1.0,
      meshSubdivide: true,
      screwHoles: true,
      screwDia: 5.0,
      baseThickness: 6,
      baseScale: 1.3,
    },
  },
];

export function getPreset(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}
