import type { Preset } from '../types';

export const PRESETS: Preset[] = [
  {
    id: 'workshop-2x4',
    name: 'Backyard 5m · 2×4',
    description: '5m V3 dome · 2×4 framing · sturdy organic timber hubs',
    settings: {
      freq: 3,
      diam: 5.0,
      trunc: 0.5,
      matType: 'rect',
      materialStockId: 'lumber-2x4',
      lumW: 38.1,
      lumH: 88.9,
      tol: 0.4,
      wall: 5,
      hubStyle: 'organic',
      bodyScale: 1.6,
      junctionMeet: 1.15,
      chamfer: 2.0,
      surfaceSmooth: 0.5,
      socketDepth: 0.9,
      meshSubdivide: true,
      screwHoles: true,
      screwDia: 4.2,
      baseThickness: 5,
      baseScale: 1.45,
    },
  },
  {
    id: 'popsicle-model',
    name: 'Popsicle Stick Dome',
    description: 'Tiny 0.5m V2 model · craft sticks · friction-fit slots, no screws',
    settings: {
      freq: 2,
      diam: 0.5,
      trunc: 0.5,
      matType: 'rect',
      materialStockId: 'craft-popsicle',
      lumW: 10,
      lumH: 2,
      tol: 0.25,
      wall: 2.2,
      hubStyle: 'organic',
      bodyScale: 1.5,
      junctionMeet: 1.15,
      chamfer: 1.0,
      surfaceSmooth: 0.5,
      socketDepth: 0.85,
      meshSubdivide: true,
      screwHoles: false,
      printFoot: true,
      baseThickness: 2,
      baseScale: 1.2,
    },
  },
  {
    id: 'straw-model',
    name: 'Straw Model Dome',
    description: 'Tiny 0.4m desktop V2 model · paper straws · friction-fit, no screws',
    settings: {
      freq: 2,
      diam: 0.4,
      trunc: 0.5,
      matType: 'round',
      materialStockId: 'straw-6mm',
      rodD: 6.0,
      tol: 0.2,
      wall: 1.8,
      hubStyle: 'organic',
      bodyScale: 1.5,
      junctionMeet: 1.0,
      chamfer: 1.0,
      surfaceSmooth: 0.6,
      socketDepth: 0.8,
      meshSubdivide: true,
      screwHoles: false,
      printFoot: true,
      baseThickness: 2,
      baseScale: 1.2,
    },
  },
  {
    id: 'greenhouse-v2',
    name: 'Greenhouse 4m V2',
    description: '4m V2 dome · 3/4" PVC · smooth organic hubs',
    settings: {
      freq: 2,
      diam: 4.0,
      trunc: 0.625,
      matType: 'round',
      materialStockId: 'pvc-0.75',
      tol: 0.3,
      wall: 4,
      hubStyle: 'organic',
      bodyScale: 1.6,
      junctionMeet: 1.0,
      chamfer: 2.0,
      surfaceSmooth: 0.65,
      socketDepth: 0.9,
      meshSubdivide: true,
      screwHoles: true,
      screwDia: 4.2,
      baseThickness: 4,
      baseScale: 1.35,
    },
  },
  {
    id: 'event-emt',
    name: 'Event 6m EMT',
    description: 'Large V3 event dome · 1" EMT · chunky blended nodes',
    settings: {
      freq: 3,
      diam: 6.0,
      trunc: 0.625,
      matType: 'round',
      materialStockId: 'emt-1',
      tol: 0.2,
      wall: 5,
      hubStyle: 'organic',
      bodyScale: 1.75,
      junctionMeet: 1.15,
      chamfer: 2.5,
      surfaceSmooth: 0.7,
      socketDepth: 0.95,
      meshSubdivide: true,
      screwHoles: true,
      screwDia: 3.3,
      baseThickness: 5,
      baseScale: 1.4,
    },
  },
  {
    id: 'playground-v1',
    name: 'Playground V1',
    description: 'Small V1 climber · 1/2" PVC · soft pebble hubs',
    settings: {
      freq: 1,
      diam: 2.5,
      trunc: 0.75,
      matType: 'round',
      materialStockId: 'pvc-0.5',
      tol: 0.35,
      wall: 4,
      hubStyle: 'organic',
      bodyScale: 1.85,
      junctionMeet: 1.2,
      chamfer: 1.5,
      surfaceSmooth: 0.85,
      socketDepth: 0.85,
      meshSubdivide: true,
      screwHoles: false,
      baseThickness: 4,
      baseScale: 1.4,
    },
  },
  {
    id: 'shed-timber-organic',
    name: 'Shed 3m Timber (Organic)',
    description: '3m dome · 1×2 lumber · blended organic sockets',
    settings: {
      freq: 2,
      diam: 3.0,
      trunc: 0.5,
      matType: 'rect',
      materialStockId: 'lumber-1x2',
      tol: 0.35,
      wall: 3.5,
      hubStyle: 'organic',
      bodyScale: 1.5,
      junctionMeet: 1.05,
      chamfer: 2.0,
      surfaceSmooth: 0.6,
      socketDepth: 0.9,
      meshSubdivide: true,
      screwHoles: true,
      screwDia: 3.3,
      baseThickness: 4,
      baseScale: 1.3,
    },
  },
  {
    id: 'shed-timber-sharp',
    name: 'Shed 3m Timber (Sharp)',
    description: '3m dome · 1×2 lumber · crisp prismatic sockets',
    settings: {
      freq: 2,
      diam: 3.0,
      trunc: 0.5,
      matType: 'rect',
      materialStockId: 'lumber-1x2',
      tol: 0.35,
      wall: 3.5,
      hubStyle: 'sharp',
      bodyScale: 1.25,
      junctionMeet: 1.1,
      chamfer: 1.5,
      surfaceSmooth: 0.3,
      socketDepth: 0.95,
      screwHoles: true,
      screwDia: 3.3,
      baseThickness: 4,
      baseScale: 1.3,
    },
  },
  {
    id: 'feel-pebble',
    name: '✨ Pebble (soft & round)',
    description: 'Smooth river-pebble hubs — organic, plump, gentle',
    settings: {
      freq: 2,
      diam: 4.0,
      trunc: 0.625,
      matType: 'round',
      materialStockId: 'pvc-0.75',
      hubStyle: 'organic',
      bodyScale: 1.85,
      surfaceSmooth: 0.85,
      strutTaper: 0.95,
      junctionMeet: 1.2,
      chamfer: 2.5,
      meshSubdivide: true,
    },
  },
  {
    id: 'feel-coral',
    name: '✨ Coral (amorphous metaball)',
    description: 'Molten, fused, sea-coral blobs — pure metaball',
    settings: {
      freq: 2,
      diam: 4.0,
      trunc: 0.625,
      matType: 'round',
      materialStockId: 'pvc-0.75',
      hubStyle: 'metaball',
      bodyScale: 1.5,
      surfaceSmooth: 0.92,
      strutTaper: 0.72,
      junctionMeet: 1.1,
      chamfer: 2,
      detail: 56,
    },
  },
  {
    id: 'feel-bone',
    name: '✨ Bone (tapered & light)',
    description: 'Tapered limbs, hollow through-core — organic skeleton',
    settings: {
      freq: 2,
      diam: 4.0,
      trunc: 0.625,
      matType: 'round',
      materialStockId: 'pvc-0.75',
      hubStyle: 'metaball',
      bodyScale: 1.3,
      surfaceSmooth: 0.65,
      strutTaper: 0.6,
      junctionMeet: 1.0,
      boreThrough: true,
      baseVent: true,
    },
  },
  {
    id: 'feel-featherweight',
    name: '✨ Featherweight (hollow)',
    description: 'Minimal filament — hollow core, vented base, soft skin',
    settings: {
      freq: 2,
      diam: 4.0,
      trunc: 0.625,
      matType: 'round',
      materialStockId: 'pvc-0.75',
      hubStyle: 'organic',
      bodyScale: 1.4,
      surfaceSmooth: 0.6,
      strutTaper: 0.8,
      boreThrough: true,
      baseVent: true,
      printInfillPct: 15,
    },
  },
  {
    id: 'feel-industrial',
    name: '✨ Industrial (crisp)',
    description: 'Tight, faceted, no-nonsense connectors — sharp CSG',
    settings: {
      freq: 2,
      diam: 4.0,
      trunc: 0.625,
      matType: 'round',
      materialStockId: 'pvc-0.75',
      hubStyle: 'sharp',
      bodyScale: 1.2,
      surfaceSmooth: 0.2,
      strutTaper: 1.0,
      junctionMeet: 1.0,
      chamfer: 1.5,
    },
  },
  {
    id: 'buckyball-goldberg',
    name: '✨ Buckyball (Goldberg)',
    description: 'True fullerene dual — hex + pentagon, all 3-way metaball hubs',
    settings: {
      freq: 3,
      diam: 5.0,
      trunc: 0.625,
      baseSolid: 'icosahedron',
      geoTopology: 'goldberg',
      matType: 'round',
      materialStockId: 'pvc-0.75',
      hubStyle: 'metaball',
      bodyScale: 1.4,
      surfaceSmooth: 0.8,
      strutTaper: 0.8,
      junctionMeet: 1.1,
    },
  },
  {
    id: 'pavilion-2x6',
    name: 'Pavilion 5m 2×6',
    description: 'Heavy V2 timber pavilion · 2×6 rafters · stout cores',
    settings: {
      freq: 2,
      diam: 5.0,
      trunc: 0.625,
      matType: 'rect',
      materialStockId: 'lumber-2x6',
      tol: 0.4,
      wall: 6,
      hubStyle: 'organic',
      bodyScale: 1.35,
      junctionMeet: 1.2,
      chamfer: 2.5,
      surfaceSmooth: 0.5,
      socketDepth: 1.0,
      meshSubdivide: true,
      screwHoles: true,
      screwDia: 5.0,
      baseThickness: 6,
      baseScale: 1.3,
    },
  },
];

export function getPreset(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}
