import type { Preset } from '../types';

export const PRESETS: Preset[] = [
  {
    id: 'greenhouse-v2',
    name: 'Greenhouse 4m V2',
    description: '4m diameter V2 dome with 3/4" PVC Sch40',
    settings: {
      freq: 2,
      diam: 4.0,
      trunc: 0.625,
      matType: 'round',
      materialStockId: 'pvc-0.75',
      tol: 0.3,
      wall: 4,
      bodyScale: 1.5,
      screwHoles: true,
      screwDia: 4.2,
    },
  },
  {
    id: 'shed-timber',
    name: 'Shed 3m Timber',
    description: '3m timber-framed shed with standard 2×4 studs',
    settings: {
      freq: 2,
      diam: 3.0,
      trunc: 0.5,
      matType: 'rect',
      materialStockId: 'lumber-2x4',
      tol: 0.4,
      wall: 5,
      bodyScale: 1.0,
      screwHoles: true,
      screwDia: 4.2,
      hubStyle: 'sharp',
    },
  },
  {
    id: 'shed-timber-organic',
    name: 'Shed 3m Timber (Organic)',
    description: '3m dome with oozy blended 2×4 timber hubs',
    settings: {
      freq: 2,
      diam: 3.0,
      trunc: 0.5,
      matType: 'rect',
      materialStockId: 'lumber-2x4',
      tol: 0.4,
      wall: 5,
      bodyScale: 1.5,
      screwHoles: true,
      screwDia: 4.2,
      hubStyle: 'organic',
    },
  },
  {
    id: 'event-emt',
    name: 'Event 6m EMT',
    description: 'Large event dome with 1" EMT conduit',
    settings: {
      freq: 3,
      diam: 6.0,
      trunc: 0.625,
      matType: 'round',
      materialStockId: 'emt-1',
      tol: 0.2,
      wall: 5,
      bodyScale: 1.6,
      screwHoles: true,
      screwDia: 3.3,
    },
  },
  {
    id: 'playground-v1',
    name: 'Playground V1',
    description: 'Small V1 climbing dome with 1/2" PVC',
    settings: {
      freq: 1,
      diam: 2.5,
      trunc: 0.75,
      matType: 'round',
      materialStockId: 'pvc-0.5',
      tol: 0.35,
      wall: 4,
      bodyScale: 1.4,
      screwHoles: false,
    },
  },
  {
    id: 'pavilion-2x6',
    name: 'Pavilion 5m 2×6',
    description: 'Heavy timber pavilion with 2×6 rafters',
    settings: {
      freq: 2,
      diam: 5.0,
      trunc: 0.625,
      matType: 'rect',
      materialStockId: 'lumber-2x6',
      tol: 0.4,
      wall: 6,
      bodyScale: 1.0,
      screwHoles: true,
      screwDia: 5.0,
    },
  },
];

export function getPreset(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}
