import type { MaterialType } from '../types';

export type MaterialCategory =
  | 'lumber'
  | 'craft'
  | 'pvc'
  | 'emt'
  | 'rod'
  | 'dowel'
  | 'straw'
  | 'fiberglass'
  | 'metaltube';

/** Real-world stock profile with actual (not nominal) dimensions in mm. */
export interface MaterialProfile {
  id: string;
  name: string;
  category: MaterialCategory;
  matType: MaterialType;
  /** Nominal trade name, e.g. "2×4" or '3/4" PVC Sch40' */
  nominal: string;
  /** Human-readable actual size */
  actualLabel: string;
  rodD?: number;
  lumW?: number;
  lumH?: number;
  /** Which lumber face is the strut length axis (depth into socket) */
  lumberDepthAxis?: 'width' | 'height';
  defaultTol: number;
  defaultWall: number;
  notes?: string;
  // ── Real material properties (for weight, strength, span, cost) ──
  /** Stock wall thickness, mm (hollow tubes only — distinct from the connector wall). */
  stockWallMm?: number;
  /** Material density, kg/m³ (PVC ~1400, softwood ~470, steel ~7850, alu ~2700). */
  densityKgM3?: number;
  /** Young's modulus, GPa (stiffness — PVC ~3, wood ~9, steel ~200). */
  elasticModulusGPa?: number;
  /** Rough price per linear metre, USD (override the global cost input). */
  costPerM?: number;
  /** Typical purchasable stock length, m. */
  stockLengthM?: number;
  /** Advisory safe unsupported span, m — warn when a strut exceeds it. */
  maxSpanM?: number;
}

/** Actual dimensions: US lumber (dry), PVC Sch40 OD, EMT OD, solid/hollow stock. */
export const MATERIAL_CATALOG: MaterialProfile[] = [
  // ── Straws & skewers — model / desktop scale ──────────────────────
  {
    id: 'skewer-3mm',
    name: 'Bamboo Skewer',
    category: 'straw',
    matType: 'round',
    nominal: '3 mm skewer',
    actualLabel: 'Ø 3.0 mm',
    rodD: 3.0,
    defaultTol: 0.15,
    defaultWall: 1.6,
    densityKgM3: 700,
    elasticModulusGPa: 17,
    costPerM: 0.1,
    stockLengthM: 0.3,
    maxSpanM: 0.12,
    notes: 'Tiny tabletop models and ornaments',
  },
  {
    id: 'straw-6mm',
    name: 'Paper Drinking Straw',
    category: 'straw',
    matType: 'round',
    nominal: '6 mm straw',
    actualLabel: 'OD 6.0 mm',
    rodD: 6.0,
    defaultTol: 0.2,
    defaultWall: 1.8,
    stockWallMm: 0.5,
    densityKgM3: 250,
    elasticModulusGPa: 2,
    costPerM: 0.05,
    stockLengthM: 0.21,
    maxSpanM: 0.15,
    notes: 'Classic straw-dome model — friction fit, no screws',
  },
  {
    id: 'straw-8mm',
    name: 'Jumbo / Boba Straw',
    category: 'straw',
    matType: 'round',
    nominal: '8 mm straw',
    actualLabel: 'OD 8.0 mm',
    rodD: 8.0,
    defaultTol: 0.2,
    defaultWall: 2,
    stockWallMm: 0.6,
    densityKgM3: 920,
    elasticModulusGPa: 1.4,
    costPerM: 0.08,
    stockLengthM: 0.24,
    maxSpanM: 0.2,
    notes: 'Bigger model domes; sturdier than a paper straw',
  },
  // ── Wood dowels & bamboo canes ────────────────────────────────────
  {
    id: 'dowel-6mm',
    name: '6 mm Wood Dowel',
    category: 'dowel',
    matType: 'round',
    nominal: '6 mm dowel',
    actualLabel: 'Ø 6.0 mm',
    rodD: 6.0,
    defaultTol: 0.25,
    defaultWall: 2.5,
    densityKgM3: 600,
    elasticModulusGPa: 10,
    costPerM: 0.4,
    stockLengthM: 0.9,
    maxSpanM: 0.4,
    notes: 'Desk models and craft domes',
  },
  {
    id: 'dowel-0.25in',
    name: '1/4" Wood Dowel',
    category: 'dowel',
    matType: 'round',
    nominal: '1/4" dowel',
    actualLabel: 'Ø 6.35 mm',
    rodD: 6.35,
    defaultTol: 0.25,
    defaultWall: 2.5,
    densityKgM3: 600,
    elasticModulusGPa: 10,
    costPerM: 0.4,
    stockLengthM: 0.9,
    maxSpanM: 0.4,
  },
  {
    id: 'dowel-0.5in',
    name: '1/2" Wood Dowel',
    category: 'dowel',
    matType: 'round',
    nominal: '1/2" dowel',
    actualLabel: 'Ø 12.7 mm',
    rodD: 12.7,
    defaultTol: 0.3,
    defaultWall: 3,
    densityKgM3: 600,
    elasticModulusGPa: 10,
    costPerM: 0.8,
    stockLengthM: 1.2,
    maxSpanM: 0.7,
    notes: 'Sturdy tabletop / small play models',
  },
  {
    id: 'dowel-0.75in',
    name: '3/4" Dowel / Broom Handle',
    category: 'dowel',
    matType: 'round',
    nominal: '3/4" dowel',
    actualLabel: 'Ø 19.05 mm',
    rodD: 19.05,
    defaultTol: 0.3,
    defaultWall: 3.5,
    densityKgM3: 600,
    elasticModulusGPa: 10,
    costPerM: 1.4,
    stockLengthM: 1.2,
    maxSpanM: 1.0,
    notes: 'Broom/closet rod — light human-scale domes',
  },
  {
    id: 'bamboo-16mm',
    name: 'Garden Bamboo Cane',
    category: 'dowel',
    matType: 'round',
    nominal: '16 mm bamboo',
    actualLabel: 'OD ~16 mm',
    rodD: 16.0,
    defaultTol: 0.6,
    defaultWall: 3,
    stockWallMm: 3,
    densityKgM3: 700,
    elasticModulusGPa: 18,
    costPerM: 0.5,
    stockLengthM: 1.8,
    maxSpanM: 1.2,
    notes: 'Cheap, light, surprisingly stiff; diameter varies',
  },
  // ── Fiberglass pultruded rod (tent-pole material) ─────────────────
  {
    id: 'fiberglass-6mm',
    name: '6 mm Fiberglass Rod',
    category: 'fiberglass',
    matType: 'round',
    nominal: '6 mm FRP',
    actualLabel: 'Ø 6.0 mm',
    rodD: 6.0,
    defaultTol: 0.2,
    defaultWall: 2.5,
    densityKgM3: 1900,
    elasticModulusGPa: 40,
    costPerM: 1.2,
    stockLengthM: 1.2,
    maxSpanM: 0.7,
    notes: 'Flexible, weatherproof — great for tensioned domes',
  },
  {
    id: 'fiberglass-10mm',
    name: '10 mm Fiberglass Rod',
    category: 'fiberglass',
    matType: 'round',
    nominal: '10 mm FRP',
    actualLabel: 'Ø 10.0 mm',
    rodD: 10.0,
    defaultTol: 0.2,
    defaultWall: 3,
    densityKgM3: 1900,
    elasticModulusGPa: 40,
    costPerM: 2.2,
    stockLengthM: 2.0,
    maxSpanM: 1.1,
    notes: 'Stiffer tent-pole stock for larger play domes',
  },
  // ── Copper & aluminum tube ────────────────────────────────────────
  {
    id: 'copper-0.75',
    name: '3/4" Copper Type M',
    category: 'metaltube',
    matType: 'round',
    nominal: '3/4" copper',
    actualLabel: 'OD 22.2 mm',
    rodD: 22.225,
    defaultTol: 0.2,
    defaultWall: 4,
    stockWallMm: 0.81,
    densityKgM3: 8960,
    elasticModulusGPa: 117,
    costPerM: 6.0,
    stockLengthM: 3.0,
    maxSpanM: 1.8,
    notes: 'Architectural / display domes — heavy, beautiful',
  },
  {
    id: 'aluminum-1',
    name: '1" Aluminum Tube',
    category: 'metaltube',
    matType: 'round',
    nominal: '1" alu tube',
    actualLabel: 'OD 25.4 mm',
    rodD: 25.4,
    defaultTol: 0.2,
    defaultWall: 4,
    stockWallMm: 1.6,
    densityKgM3: 2700,
    elasticModulusGPa: 69,
    costPerM: 4.0,
    stockLengthM: 3.6,
    maxSpanM: 2.0,
    notes: 'Light, stiff, corrosion-proof — premium portable domes',
  },
  // ── Craft & popsicle sticks — flat, thin, model scale ─────────────
  {
    id: 'craft-popsicle',
    name: 'Popsicle / Craft Stick',
    category: 'craft',
    matType: 'rect',
    nominal: 'popsicle stick',
    actualLabel: '10 × 2 mm (≈4.5" long)',
    lumW: 10,
    lumH: 2,
    lumberDepthAxis: 'height',
    defaultTol: 0.25,
    defaultWall: 2.2,
    densityKgM3: 600,
    elasticModulusGPa: 10,
    costPerM: 0.3,
    stockLengthM: 0.114,
    maxSpanM: 0.18,
    notes: 'Classic model domes — friction-fit slots, no screws',
  },
  {
    id: 'craft-jumbo',
    name: 'Jumbo Craft Stick',
    category: 'craft',
    matType: 'rect',
    nominal: 'jumbo stick',
    actualLabel: '18 × 2 mm (≈6" long)',
    lumW: 18,
    lumH: 2,
    lumberDepthAxis: 'height',
    defaultTol: 0.25,
    defaultWall: 2.4,
    densityKgM3: 600,
    elasticModulusGPa: 10,
    costPerM: 0.4,
    stockLengthM: 0.15,
    maxSpanM: 0.22,
    notes: 'Bigger model domes; sturdier than a popsicle stick',
  },
  {
    id: 'craft-paint-stir',
    name: 'Paint Stirrer',
    category: 'craft',
    matType: 'rect',
    nominal: 'paint stirrer',
    actualLabel: '19 × 3 mm (≈12" long)',
    lumW: 19,
    lumH: 3,
    lumberDepthAxis: 'height',
    defaultTol: 0.3,
    defaultWall: 2.6,
    densityKgM3: 600,
    elasticModulusGPa: 10,
    costPerM: 0.5,
    stockLengthM: 0.3,
    maxSpanM: 0.4,
    notes: 'Free at the hardware store; great mid-size model stock',
  },
  // ── Lumber (actual cross-section, mm) — small to large ───────────
  {
    id: 'lumber-1x2',
    name: '1×2 Furring / Light Frame',
    category: 'lumber',
    matType: 'rect',
    nominal: '1×2',
    actualLabel: '19 × 38 mm (0.75" × 1.5")',
    lumW: 19.05,
    lumH: 38.1,
    lumberDepthAxis: 'height',
    defaultTol: 0.35,
    defaultWall: 3.5,
    densityKgM3: 470,
    elasticModulusGPa: 9,
    costPerM: 1.2,
    stockLengthM: 2.4,
    maxSpanM: 1.5,
    notes: 'Light domes, models, garden structures',
  },
  {
    id: 'lumber-1x3',
    name: '1×3 Board',
    category: 'lumber',
    matType: 'rect',
    nominal: '1×3',
    actualLabel: '19 × 64 mm (0.75" × 2.5")',
    lumW: 19.05,
    lumH: 63.5,
    lumberDepthAxis: 'height',
    defaultTol: 0.4,
    defaultWall: 4,
    densityKgM3: 470,
    elasticModulusGPa: 9,
    costPerM: 1.6,
    stockLengthM: 2.4,
    maxSpanM: 1.8,
    notes: 'Mid-weight frames and bracing',
  },
  {
    id: 'lumber-1x4',
    name: '1×4 Furring Strip',
    category: 'lumber',
    matType: 'rect',
    nominal: '1×4',
    actualLabel: '19 × 89 mm (0.75" × 3.5")',
    lumW: 19.05,
    lumH: 88.9,
    lumberDepthAxis: 'height',
    defaultTol: 0.5,
    defaultWall: 4,
    densityKgM3: 470,
    elasticModulusGPa: 9,
    costPerM: 2.0,
    stockLengthM: 3.0,
    maxSpanM: 2.0,
    notes: 'Purlins, cladding battens',
  },
  {
    id: 'lumber-1x6',
    name: '1×6 Board',
    category: 'lumber',
    matType: 'rect',
    nominal: '1×6',
    actualLabel: '19 × 140 mm (0.75" × 5.5")',
    lumW: 19.05,
    lumH: 139.7,
    lumberDepthAxis: 'height',
    defaultTol: 0.5,
    defaultWall: 4,
    densityKgM3: 470,
    elasticModulusGPa: 9,
    costPerM: 3.0,
    stockLengthM: 3.0,
    maxSpanM: 2.2,
    notes: 'Wide battens, shelf-like ribs',
  },
  {
    id: 'lumber-2x3',
    name: '2×3 Light Stud',
    category: 'lumber',
    matType: 'rect',
    nominal: '2×3',
    actualLabel: '38 × 64 mm (1.5" × 2.5")',
    lumW: 38.1,
    lumH: 63.5,
    lumberDepthAxis: 'height',
    defaultTol: 0.4,
    defaultWall: 5,
    densityKgM3: 470,
    elasticModulusGPa: 9,
    costPerM: 1.8,
    stockLengthM: 2.4,
    maxSpanM: 2.2,
    notes: 'Lighter framing, partition studs',
  },
  {
    id: 'lumber-2x4',
    name: '2×4 Stud / Framing',
    category: 'lumber',
    matType: 'rect',
    nominal: '2×4',
    actualLabel: '38 × 89 mm (1.5" × 3.5")',
    lumW: 38.1,
    lumH: 88.9,
    lumberDepthAxis: 'height',
    defaultTol: 0.4,
    defaultWall: 5,
    densityKgM3: 470,
    elasticModulusGPa: 9,
    costPerM: 2.5,
    stockLengthM: 2.4,
    maxSpanM: 3.0,
    notes: 'Heavy framing, large sheds — the classic dome stick',
  },
  {
    id: 'lumber-2x6',
    name: '2×6 Framing',
    category: 'lumber',
    matType: 'rect',
    nominal: '2×6',
    actualLabel: '38 × 140 mm (1.5" × 5.5")',
    lumW: 38.1,
    lumH: 139.7,
    lumberDepthAxis: 'height',
    defaultTol: 0.4,
    defaultWall: 5,
    densityKgM3: 470,
    elasticModulusGPa: 9,
    costPerM: 4.0,
    stockLengthM: 3.0,
    maxSpanM: 4.0,
    notes: 'Heavier rafters and floor joists',
  },
  {
    id: 'lumber-2x8',
    name: '2×8 Beam',
    category: 'lumber',
    matType: 'rect',
    nominal: '2×8',
    actualLabel: '38 × 184 mm (1.5" × 7.25")',
    lumW: 38.1,
    lumH: 184.15,
    lumberDepthAxis: 'height',
    defaultTol: 0.4,
    defaultWall: 6,
    densityKgM3: 470,
    elasticModulusGPa: 9,
    costPerM: 5.5,
    stockLengthM: 3.6,
    maxSpanM: 4.8,
    notes: 'Large-span ribs and base beams',
  },
  // ── PVC Schedule 40 (outer diameter, mm) ──────────────────────────
  {
    id: 'pvc-0.5',
    name: '1/2" PVC Sch40',
    category: 'pvc',
    matType: 'round',
    nominal: '1/2" PVC',
    actualLabel: 'OD 21.3 mm',
    rodD: 21.34,
    defaultTol: 0.35,
    defaultWall: 4,
    stockWallMm: 2.77,
    densityKgM3: 1400,
    elasticModulusGPa: 3,
    costPerM: 1.0,
    stockLengthM: 3.0,
    maxSpanM: 0.9,
    notes: 'Light garden domes, small prototypes',
  },
  {
    id: 'pvc-0.75',
    name: '3/4" PVC Sch40',
    category: 'pvc',
    matType: 'round',
    nominal: '3/4" PVC',
    actualLabel: 'OD 26.7 mm',
    rodD: 26.67,
    defaultTol: 0.3,
    defaultWall: 4,
    stockWallMm: 2.87,
    densityKgM3: 1400,
    elasticModulusGPa: 3,
    costPerM: 1.3,
    stockLengthM: 3.0,
    maxSpanM: 1.2,
    notes: 'Common DIY geodesic conduit',
  },
  {
    id: 'pvc-1',
    name: '1" PVC Sch40',
    category: 'pvc',
    matType: 'round',
    nominal: '1" PVC',
    actualLabel: 'OD 33.4 mm',
    rodD: 33.4,
    defaultTol: 0.3,
    defaultWall: 5,
    stockWallMm: 3.38,
    densityKgM3: 1400,
    elasticModulusGPa: 3,
    costPerM: 1.8,
    stockLengthM: 3.0,
    maxSpanM: 1.6,
    notes: 'Greenhouses and medium domes',
  },
  {
    id: 'pvc-1.25',
    name: '1-1/4" PVC Sch40',
    category: 'pvc',
    matType: 'round',
    nominal: '1-1/4" PVC',
    actualLabel: 'OD 42.2 mm',
    rodD: 42.16,
    defaultTol: 0.25,
    defaultWall: 5,
    stockWallMm: 3.56,
    densityKgM3: 1400,
    elasticModulusGPa: 3,
    costPerM: 2.5,
    stockLengthM: 3.0,
    maxSpanM: 2.0,
  },
  {
    id: 'pvc-1.5',
    name: '1-1/2" PVC Sch40',
    category: 'pvc',
    matType: 'round',
    nominal: '1-1/2" PVC',
    actualLabel: 'OD 48.3 mm',
    rodD: 48.26,
    defaultTol: 0.25,
    defaultWall: 5.5,
    stockWallMm: 3.68,
    densityKgM3: 1400,
    elasticModulusGPa: 3,
    costPerM: 3.0,
    stockLengthM: 3.0,
    maxSpanM: 2.4,
    notes: 'Larger walk-in domes',
  },
  {
    id: 'pvc-2',
    name: '2" PVC Sch40',
    category: 'pvc',
    matType: 'round',
    nominal: '2" PVC',
    actualLabel: 'OD 60.3 mm',
    rodD: 60.32,
    defaultTol: 0.25,
    defaultWall: 6,
    stockWallMm: 3.91,
    densityKgM3: 1400,
    elasticModulusGPa: 3,
    costPerM: 4.0,
    stockLengthM: 3.0,
    maxSpanM: 3.0,
    notes: 'Big structural domes; heavier hubs',
  },
  // ── EMT electrical conduit (outer diameter, mm) ───────────────────
  {
    id: 'emt-0.5',
    name: '1/2" EMT Conduit',
    category: 'emt',
    matType: 'round',
    nominal: '1/2" EMT',
    actualLabel: 'OD 18.3 mm',
    rodD: 18.29,
    defaultTol: 0.2,
    defaultWall: 4,
    stockWallMm: 1.07,
    densityKgM3: 7850,
    elasticModulusGPa: 200,
    costPerM: 1.2,
    stockLengthM: 3.05,
    maxSpanM: 1.5,
    notes: 'Thin-wall steel, strong for weight',
  },
  {
    id: 'emt-0.75',
    name: '3/4" EMT Conduit',
    category: 'emt',
    matType: 'round',
    nominal: '3/4" EMT',
    actualLabel: 'OD 23.1 mm',
    rodD: 23.11,
    defaultTol: 0.2,
    defaultWall: 4,
    stockWallMm: 1.25,
    densityKgM3: 7850,
    elasticModulusGPa: 200,
    costPerM: 1.6,
    stockLengthM: 3.05,
    maxSpanM: 1.9,
  },
  {
    id: 'emt-1',
    name: '1" EMT Conduit',
    category: 'emt',
    matType: 'round',
    nominal: '1" EMT',
    actualLabel: 'OD 29.5 mm',
    rodD: 29.46,
    defaultTol: 0.2,
    defaultWall: 5,
    stockWallMm: 1.5,
    densityKgM3: 7850,
    elasticModulusGPa: 200,
    costPerM: 2.2,
    stockLengthM: 3.05,
    maxSpanM: 2.4,
    notes: 'Event domes and climbing frames',
  },
  {
    id: 'emt-1.25',
    name: '1-1/4" EMT Conduit',
    category: 'emt',
    matType: 'round',
    nominal: '1-1/4" EMT',
    actualLabel: 'OD 38.4 mm',
    rodD: 38.35,
    defaultTol: 0.2,
    defaultWall: 5,
    stockWallMm: 1.65,
    densityKgM3: 7850,
    elasticModulusGPa: 200,
    costPerM: 3.2,
    stockLengthM: 3.05,
    maxSpanM: 3.0,
    notes: 'Large, strong steel domes',
  },
  // ── Solid metal rod ───────────────────────────────────────────────
  {
    id: 'rod-6mm',
    name: '6 mm Solid Rod',
    category: 'rod',
    matType: 'round',
    nominal: '6 mm rod',
    actualLabel: 'Ø 6.0 mm',
    rodD: 6.0,
    defaultTol: 0.15,
    defaultWall: 3,
    densityKgM3: 7850,
    elasticModulusGPa: 200,
    costPerM: 1.0,
    stockLengthM: 1.0,
    maxSpanM: 0.5,
    notes: 'Mild steel or aluminum rod',
  },
  {
    id: 'rod-8mm',
    name: '8 mm Solid Rod',
    category: 'rod',
    matType: 'round',
    nominal: '8 mm rod',
    actualLabel: 'Ø 8.0 mm',
    rodD: 8.0,
    defaultTol: 0.15,
    defaultWall: 3.5,
    densityKgM3: 7850,
    elasticModulusGPa: 200,
    costPerM: 1.6,
    stockLengthM: 1.0,
    maxSpanM: 0.6,
  },
  {
    id: 'rod-10mm',
    name: '10 mm Solid Rod',
    category: 'rod',
    matType: 'round',
    nominal: '10 mm rod',
    actualLabel: 'Ø 10.0 mm',
    rodD: 10.0,
    defaultTol: 0.15,
    defaultWall: 4,
    densityKgM3: 7850,
    elasticModulusGPa: 200,
    costPerM: 2.4,
    stockLengthM: 1.0,
    maxSpanM: 0.75,
  },
  {
    id: 'rod-0.25in',
    name: '1/4" Solid Rod',
    category: 'rod',
    matType: 'round',
    nominal: '1/4" rod',
    actualLabel: 'Ø 6.35 mm',
    rodD: 6.35,
    defaultTol: 0.15,
    defaultWall: 3,
    densityKgM3: 7850,
    elasticModulusGPa: 200,
    costPerM: 1.1,
    stockLengthM: 1.0,
    maxSpanM: 0.5,
  },
  {
    id: 'rod-0.375in',
    name: '3/8" Solid Rod',
    category: 'rod',
    matType: 'round',
    nominal: '3/8" rod',
    actualLabel: 'Ø 9.53 mm',
    rodD: 9.53,
    defaultTol: 0.15,
    defaultWall: 3.5,
    densityKgM3: 7850,
    elasticModulusGPa: 200,
    costPerM: 2.2,
    stockLengthM: 1.0,
    maxSpanM: 0.7,
  },
  {
    id: 'rod-0.5in',
    name: '1/2" Solid Rod',
    category: 'rod',
    matType: 'round',
    nominal: '1/2" rod',
    actualLabel: 'Ø 12.7 mm',
    rodD: 12.7,
    defaultTol: 0.15,
    defaultWall: 4,
    densityKgM3: 7850,
    elasticModulusGPa: 200,
    costPerM: 3.5,
    stockLengthM: 1.0,
    maxSpanM: 0.9,
  },
];

export const CATEGORY_LABELS: Record<MaterialCategory, string> = {
  straw: 'Straws & Skewers (models)',
  craft: 'Craft & Popsicle Sticks',
  dowel: 'Wood Dowel & Bamboo',
  fiberglass: 'Fiberglass Rod',
  metaltube: 'Copper & Aluminum Tube',
  lumber: 'Lumber (actual dims)',
  pvc: 'PVC Pipe — Sch40 OD',
  emt: 'EMT Metal Conduit',
  rod: 'Solid Metal Rod',
};

export function getMaterialProfile(id: string): MaterialProfile | undefined {
  return MATERIAL_CATALOG.find((m) => m.id === id);
}

export function getMaterialsByCategory(matType?: MaterialType): Map<MaterialCategory, MaterialProfile[]> {
  const map = new Map<MaterialCategory, MaterialProfile[]>();
  for (const m of MATERIAL_CATALOG) {
    if (matType && m.matType !== matType) continue;
    if (!map.has(m.category)) map.set(m.category, []);
    map.get(m.category)!.push(m);
  }
  return map;
}

export function defaultStockForMatType(matType: MaterialType): string {
  return matType === 'rect' ? 'lumber-1x2' : 'pvc-0.75';
}

export interface MaterialStockPatch {
  matType: MaterialType;
  rodD: number;
  lumW: number;
  lumH: number;
  tol: number;
  wall: number;
  materialStockId: string;
  lumberDepthAxis?: 'width' | 'height';
  /** Only set when the profile carries its own stock length / price. */
  stockLength?: number;
  stockPrice?: number;
}

export function applyMaterialProfile(profile: MaterialProfile): MaterialStockPatch {
  const patch: MaterialStockPatch = {
    matType: profile.matType,
    rodD: profile.rodD ?? 26.67,
    lumW: profile.lumW ?? 19.05,
    lumH: profile.lumH ?? 38.1,
    tol: profile.defaultTol,
    wall: profile.defaultWall,
    materialStockId: profile.id,
    lumberDepthAxis: profile.lumberDepthAxis,
  };
  if (profile.stockLengthM) patch.stockLength = profile.stockLengthM;
  if (profile.costPerM && profile.stockLengthM) {
    patch.stockPrice = Math.round(profile.costPerM * profile.stockLengthM * 100) / 100;
  }
  return patch;
}
