export {
  SETTINGS_SCHEMA_VERSION,
  loadSettings,
  saveSettings,
  clearSettings,
  settingsShareHash,
  normalizeSettings,
  parseDesignJson,
  importDesignJson,
  loadCustomPresets,
  saveCustomPresets,
  addCustomPreset,
  designJsonMeta,
  type DesignJsonDocument,
  type CustomPreset,
} from './settings-schema';
